#!/bin/sh

trayer --expand true --transparent true --alpha 0 --tint $TRAYER_TINT \
    --edge bottom --align right --SetPartialStrut true &

# Programs below should always be present

gnome-settings-daemon 2>/dev/null &
/usr/lib/gnome-settings-daemon/gnome-settings-daemon 2>/dev/null &

nm-applet &
system-config-printer-applet &


# Depending on the version of Gnome, let's start a bunch of tools

which gnome-power-manager > /dev/null \
    && gnome-power-manager &

which gnome-volume-control-applet > /dev/null \
    && gnome-volume-control-applet &

which gnome-sound-applet > /dev/null \
    && gnome-sound-applet &

# Start the Keyring daemon because it's friendly

export `gnome-keyring-daemon`
