#!/bin/sh

inbox() {
    value=$(grep -c '^X-Mozilla-Status: 0000' ~/.thunderbird/bjk2k39u.default/Mail/mail.almacom.co.th/Inbox)

    if [ "$value" != "0" ]; then
        echo 'inbox:' $value '|'
    fi
}

battery() {
    capacity=$(cat  /sys/class/power_supply/BAT1/energy_full)
    remaining=$(cat /sys/class/power_supply/BAT1/energy_now)

    echo 'battery:' "$((100 * $remaining / $capacity))%"
}

load() {
    echo 'load:' $(uptime | sed 's/.*://; s/,.*//g')
}

clock() {
    echo $(date +%Y-%m-%d\ %H:%M)
}

wlan0() {
    echo wlan0: $(iwconfig wlan0 | awk '/Quality/{print $2}' | sed 's/.*=//' | awk -F"/" '{printf("%.0f%%", $1/$2*100)}') $(iwconfig wlan0 | grep ESSID | awk -F'"' '{ print $2 }') $(ifconfig wlan0 | grep inet\\b | awk '{ print $2}')
}

echo -n $(wlan0) '|' $(battery) '|' $(load) '|' $(clock)

# This script will run every second in recent versions. As we certainly don't
# require such a low refresh rate, let's put it to sleep.
sleep 29
