#!/bin/sh

MODKEY=Mod1

WMII_TERM=gnome-terminal

WMII_NORMCOLORS='#888888 #222222 #222222'
WMII_FOCUSCOLORS='#ffffff #222222 #222222'

WMII_BACKGROUND='#333333'
WMII_FONT='Monospace'


# Status bar
# ----------

WITH_BATTERY=
if [ -d /sys/class/power_supply/BAT1 ]; then
    WITH_BATTERY=yes
fi

battery() {
    capacity=$(cat  /sys/class/power_supply/BAT1/energy_full)
    remaining=$(cat /sys/class/power_supply/BAT1/energy_now)

    echo "$((100 * $remaining / $capacity))%"
}

load() {
    echo $(uptime | sed 's/.*://; s/,.*//g')
}

clock() {
    echo $(date +%a\ %Y-%m-%d\ %H:%M:%S)
}

net() {
    ping -c 1 xanax.xyz &>/dev/null

    if [ "$?" != "0" ]; then
        echo 'OFFLINE |'
    fi
}

status() {
    if [ "$WITH_BATTERY" ]; then
        echo -n label $(net) $(battery) '|' $(load) '|' $(clock)
    else
        echo -n label $(net) $(load) '|' $(clock)
    fi

    sleep 59 # Main `wmiirc` sleeps for 1s already.
}


# Applications startup
# --------------------

run_if_exists() {
    which $1 &>/dev/null && $1 &
}

run_if_exists gnome-power-manager
run_if_exists gnome-settings-daemon
run_if_exists gnome-sound-applet
run_if_exists gnome-volume-control-applet
run_if_exists nm-applet
run_if_exists system-config-printer-applet

# Keyboard repeat/trigger rate
set r rate 400 50

export `gnome-keyring-daemon`
