#!/bin/sh

set -e

running_sinks()
{
  pactl list sinks short | awk '/RUNNING/ {print $1}'
}

case "$1" in
  toggle-mute)
    running_sinks | xargs -I '{}' pactl set-sink-mute {} toggle
    ;;

  lower-volume)
    running_sinks | xargs -I '{}' pactl set-sink-volume {} -5%
    ;;

  raise-volume)
    running_sinks | xargs -I '{}' pactl set-sink-volume {} +5%
    ;;
esac
