#!/usr/bin/env python

import datetime
import subprocess


def echo(*items, separator=None):
    if separator is None:
        separator = ' '

    print(
        separator.join(x for x in items if x)
    )


def exec(command):
    try:
        stdout = subprocess.check_output(
            command, stderr=subprocess.STDOUT, shell=True
        )

        return stdout.decode("utf-8").strip()
    except Exception:
        pass


def widget_music():
    song = exec("rhythmbox-client --no-start --print-playing")

    setattr(widget_music, "cache", song)

    if not song or song == "-":
        return

    if len(song) > 96:
        song = song[:96] + "..."

    return " [ " + song + " ] "


def widget_clock(format="%Y-%m-%d %H:%M"):
    return datetime.datetime.now().strftime(format)


def widget_volume():
    volume = exec("~/.config/i3/audio volume")

    try:
        volume = volume.rstrip("%")
        volume = int(volume)

        return "{}% ".format(volume)
    except Exception:
        return ""


def widget_ethernet():
    with open("/proc/net/dev") as file:
        for line in file.readlines():
            fields = line.split(":", 1)

            if fields[0].strip().startswith("enp"):
                break
        else:
            return

    return ""


if __name__ == "__main__":
    echo(
        widget_music(),
        widget_volume(),
        widget_ethernet(),
    )
