#!/bin/sh -e

URLS=(
  https://github.com/tpope/vim-pathogen.git

  # Color scheme
  https://github.com/saalaa/ancient-colors.vim.git

  # Advanced vim features
  https://github.com/kien/ctrlp.vim.git
  https://github.com/mileszs/ack.vim.git
  https://github.com/saalaa/WoodenView.vim.git

  # Edition assistance
  https://github.com/tpope/vim-commentary.git

  # Generic syntax checker
  https://github.com/scrooloose/syntastic.git

  # Languages support
  https://github.com/aaronj1335/underscore-templates.vim.git
  https://github.com/digitaltoad/vim-jade.git
  https://github.com/glench/vim-jinja2-syntax.git
  https://github.com/groenewege/vim-less.git
  https://github.com/rust-lang/rust.vim.git
  https://github.com/sophacles/vim-bundle-mako.git

  # https://github.com/sgur/ctrlp-extensions.vim.git
  # https://github.com/mattn/ctrlp-launcher.git
  # https://github.com/tpope/vim-fugitive.git
  # https://github.com/gregsexton/gitv.git
  # https://github.com/junegunn/goyo.vim.git
  # https://github.com/mattn/gist-vim.git
  # https://github.com/tpope/vim-fireplace.git
  # https://github.com/sjl/gundo.vim.git
  # https://github.com/mattn/webapi-vim.git
)

if [ ! -d ~/.vim/bundle ]; then
  echo Error: bundle directory does not exist
  exit 1
fi

for url in ${URLS[@]}; do
  echo Fetching $url

  (cd ~/.vim/bundle && \
    git clone -q $url | sed 's/^/  | /')
done
