" Only Apple screens are crisp enough for light themes
if has("gui_macvim")
  set background=light
  " colorscheme base16-ocean
else
  set background=dark
  " colorscheme base16-twilight
end

" Remove menubar and toolbar on GNU/Linux
if has("gui_gtk2")
  set guioptions-=m
  set guioptions-=T
end

" Remove scrollbars
set guioptions-=L
set guioptions-=r

" Cross-platform typography
if has("gui_gtk2")
    set guifont=Droid\ Sans\ Mono\ 11
elseif has("gui_macvim")
    set guifont=Droid\ Sans\ Mono:h13
elseif has("gui_win32")
    set guifont=Droid\ Sans\ Mono:h13
end

" Highlight eol, etc..
hi SpecialKey guifg=white guibg=gray
