#!/bin/sh -e

if [ ! -d ~/.vim/bundle ]; then
  echo Error: bundle directory does not exist
  exit 1
fi

for item in ~/.vim/bundle/*; do
  if [ ! -d $item ]; then
    continue
  fi

  echo Updating $item

  (cd $item && \
    git pull | sed 's/^/  | /')
done

# Update helptags on plugins
vim -c Helptags -c q
