#!/bin/sh

set -e

list_sinks()
{
  pactl list sinks short | awk '{print $1}'
}

sinks_ctl()
{
  for sink in $(list_sinks); do
    echo pactl "$@" | sed "s/{}/$sink/" | sh
  done
}

case "$1" in
  stop)
    rhythmbox-client --stop
    ;;

  play-pause)
    rhythmbox-client --play-pause
    ;;

  previous)
    rhythmbox-client --previous
    ;;

  next)
    rhythmbox-client --next
    ;;

  volume)
    muted=$(pactl list sinks | awk '/Mute/{ print $2; exit }')

    if [ "$muted" = "yes" ]; then
      echo muted
      exit
    fi

    pactl list sinks | awk '/Base Volume/{ print $5; exit }'
    ;;

  toggle-mute)
    sinks_ctl "set-sink-mute {} toggle"
    ;;

  lower-volume)
    sinks_ctl "set-sink-volume {} -5%"
    ;;

  raise-volume)
    sinks_ctl "set-sink-volume {} +5%"
    ;;

  *)
    echo 'Usage: audio stop | play-pause | previous | next | volume | ' \
      'toggle-mute | lower-volume | raise-volume'
esac
