#!/bin/sh -e

if [ ! -d ~/.config/i3 ]; then
  mkdir -p ~/.config/i3
fi

ln -s `pwd`/config  ~/.config/i3
ln -s `pwd`/status  ~/.config/i3

ln -s `pwd`/audio  ~/.config/i3
ln -s `pwd`/omenu  ~/.config/i3
ln -s `pwd`/pmenu  ~/.config/i3

ln -s `pwd`/shortcuts  ~/.config/i3
