#!/bin/sh

set -e

list_sinks()
{
  pactl list sinks short | awk '{print $1}'
}

sinks_ctl()
{
  for sink in $(list_sinks); do
    echo pactl "$@" | sed "s/{}/$sink/" | sh
  done
}

case "$1" in
  toggle-mute)
    sinks_ctl "set-sink-mute {} toggle"
    ;;

  lower-volume)
    sinks_ctl "set-sink-volume {} -5%"
    ;;

  raise-volume)
    sinks_ctl "set-sink-volume {} +5%"
    ;;
esac
