#!/bin/sh

set -e

case "$1" in
  stop)
    dbus-send --print-reply --dest=net.sacredchao.QuodLibet \
      /net/sacredchao/QuodLibet net.sacredchao.QuodLibet.Pause
    ;;

  play-pause)
    dbus-send --print-reply --dest=net.sacredchao.QuodLibet \
      /net/sacredchao/QuodLibet net.sacredchao.QuodLibet.PlayPause
    ;;

  previous)
    dbus-send --print-reply --dest=net.sacredchao.QuodLibet \
      /net/sacredchao/QuodLibet net.sacredchao.QuodLibet.Previous
    ;;

  next)
    dbus-send --print-reply --dest=net.sacredchao.QuodLibet \
      /net/sacredchao/QuodLibet net.sacredchao.QuodLibet.Next
    ;;
esac
