#!/bin/sh

mkdir ~/.mutt ~/.mutt/cache

ln -s `pwd`/muttrc    ~/.muttrc
ln -s `pwd`/signature ~/.signature
ln -s `pwd`/aliases   ~/.aliases

ln -s `pwd`/mailcap     ~/.mutt
ln -s `pwd`/open.sh     ~/.mutt

ln -s `pwd`/*.muttrc ~/.mutt
