- name: Install docker.io
  apt:
    name: "docker.io"
    state: present
  become: yes

- name: User in docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: "docker"
    append: yes
  become: yes


- name: Download argocd
  uri:
    url: "https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64"
    dest: "{{ home }}/bin/argocd"
    status_code: [200, 304]
    mode: '755'

- name: Download docker-compose
  uri:
    url: "https://github.com/docker/compose/releases/download/{{ versions.compose }}/docker-compose-linux-x86_64"
    dest: "{{ home }}/bin/docker-compose"
    status_code: [200, 304]
    mode: '755'

- name: Download kubectl
  uri:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ versions.kubectl }}/bin/linux/amd64/kubectl"
    dest: "{{ home }}/bin/kubectl"
    status_code: [200, 304]
    mode: '755'

- name: Download minikube
  uri:
    url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
    dest: "{{ home }}/bin/minikube"
    status_code: [200, 304]
    mode: '755'
