#!/bin/sh

if [ -e ~/.tmux.conf ]; then
  mv ~/.tmux.conf ~/.tmux.conf.bak.$$
fi

ln -s `pwd`/tmux.conf ~/.tmux.conf

ln -s `pwd`/tmux-ancient.conf ~/.tmux-ancient.conf
ln -s `pwd`/tmux-paramount.conf ~/.tmux-paramount.conf
