# Oh My ZSH! path
ZSH=$HOME/.oh-my-zsh

# More themes in ~/.oh-my-zsh/themes/ (or `random`)
ZSH_THEME="terminalparty"

# Use case-sensitive completion
CASE_SENSITIVE="true"

# Disable auto-update checks
DISABLE_AUTO_UPDATE="true"

# Disable command autocorrection
DISABLE_CORRECTION="true"

# More plugins in ~/.oh-my-zsh/plugins/
plugins=(git)

# Load Oh My ZSH!
source $ZSH/oh-my-zsh.sh

# Override theme dirty git marker
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[red]%}!%{$fg[yellow]%}"

# Custom path
export PATH=$PATH:/bin
export PATH=$PATH:/usr/bin
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/sbin
export PATH=$PATH:/usr/sbin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/node_modules/.bin
export PATH=$PATH:node_modules/.bin

# Concurrent ZSH / messed history fix
setopt no_share_history
unsetopt share_history

# Attempt to disable control flow in order to prevent vim from hanging. This of
# course doesn't really work.
stty stop undef
stty start undef
